dist: trusty
sudo: required
addons:
  postgresql: "9.5"

language: php

php:
  - 5.6
  - 7.0

install:
  - composer install

script: phpunit --coverage-text

services:
  - postgresql

before_script:
  - psql -c 'create database gonzalo;' -U postgres
  - psql -c 'create role username LOGIN;' -U postgres

