sudo: false

language: php

php:
  - 5.6
  - 7.0

install:
  - composer install

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

script: phpunit --coverage-text

services:
  - postgresql

before_script:
  - psql -c 'create database gonzalo;' -U postgres
  - psql -c 'create role username LOGIN;' -U postgres

