sudo: false

language: php

php:
  - 5.6
  - 7.0

install:
  - composer install

script: phpunit --coverage-text

services:
  - postgresql

before_script:
  - psql -c 'create database gonzalo;' -U postgres

